services:
  dev:
    image: node
    entrypoint:
    command: npm run serve
    volumes:
      - .:$PWD
    working_dir: $PWD # in order to eslint work together with local editor
    ports:
      - 8000:8000