name: app-build
on:
  push:
    branches:
      - main
      - develop
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: yarn && yarn build
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - uses: actions/upload-artifact@v4
        with:
          name: consent-banner.bundle.min.js
          path: dist/consent-banner-js/${{ steps.package-version.outputs.current-version}}/consent-banner.bundle.min.js
      - uses: actions/upload-artifact@v4
        with:
          name: consent-banner.min.js
          path: dist/consent-banner-js/${{ steps.package-version.outputs.current-version}}/consent-banner.min.js
      - uses: actions/upload-artifact@v4
        with:
          name: light.css
          path: dist/consent-banner-js/${{ steps.package-version.outputs.current-version}}/styles/light.css
